import {
  Activity, ArrowDown, ArrowLeft, ArrowRight, ArrowUp, BookOpen, Check,
  ChevronDown, ChevronLeft, ChevronRight, ChevronUp, Circle, ClipboardList, Clock, Coins,
  Copy, CornerDownLeft, Cpu, DollarSign, Folder, GitBranch, Keyboard, LayoutGrid, Link2,
  ListFilter, Maximize2, MemoryStick, Mic, Minus, MoreHorizontal, Pencil, Play, Plus,
  RefreshCw, Rocket, Search, Send, Settings, Skull, Sparkles, Square, StickyNote, Car,
  Terminal, Trash2, TriangleAlert, Tv, User, Users, X, Zap, Microscope, FileText,
} from 'lucide-react';

// Semantic name → lucide glyph. Views ask for meaning ("launch", "needs you"),
// never for a specific drawing, so the icon set can be retuned in one place.
const MAP = {
  agents: LayoutGrid,
  overview: Activity,
  library: BookOpen,
  launch: Rocket,
  mic: Mic,
  settings: Settings,
  car: Car,
  tv: Tv,
  terminal: Terminal,
  expand: Maximize2,
  close: X,
  back: ChevronLeft,
  plan: ClipboardList,
  research: Microscope,
  note: StickyNote,
  doc: FileText,
  play: Play,
  stop: Square,
  kill: Skull,
  send: Send,
  search: Search,
  plus: Plus,
  minus: Minus,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  chevronDown: ChevronDown,
  check: Check,
  alert: TriangleAlert,
  cpu: Cpu,
  memory: MemoryStick,
  clock: Clock,
  dollar: DollarSign,
  tokens: Coins,
  branch: GitBranch,
  folder: Folder,
  user: User,
  users: Users,
  bolt: Zap,
  sparkles: Sparkles,
  keyboard: Keyboard,
  copy: Copy,
  link: Link2,
  refresh: RefreshCw,
  more: MoreHorizontal,
  filter: ListFilter,
  edit: Pencil,
  trash: Trash2,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  enter: CornerDownLeft,
  esc: X,
};

export default function Icon({ name, size = 18, strokeWidth = 1.75, ...rest }) {
  const C = MAP[name] || Circle;
  return <C size={size} strokeWidth={strokeWidth} aria-hidden="true" {...rest} />;
}
